name: Run tests

on:
  push:
    branches: [master]
    tags:
      - "*"

jobs:
  test-release:
    name: Test release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
        id: go

      - name: Check formatting
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

      - name: Run tests
        run: |
          go test .

      - name: Build release
        run: |
          make build-all

      - name: Smoketest release
        run: |
          make smoketest
